#
# This is a Nuage Application HOT template just defining an application 
# with two tiers and flow between them
#
heat_template_version: 2015-04-30

parameters:
  flavor:
    type: string
    default: m1.heat
  image:
    type: string
    default: cirros-0.3.2-x86_64-uec

resources:

  mysql_svc:
    type: Nuage::Neutron::ApplicationService
    properties:
      name: mysql
      description: 'mysql db connection service'
      protocol: tcp
      src_port: '*'
      dest_port: 3306

  app_domain:
    type: Nuage::Neutron::ApplicationDomain
    properties:
      name: 'Wordpress'

  app:
    type: Nuage::Neutron::Application
    properties:
      name: 'WordpressApp'
      description: 'my Cool App'
      applicationdomain_id: { get_resource: app_domain }

  web_tier:
    type: Nuage::Neutron::ApplicationTier
    properties:
      name: web_tier
      app_id: { get_resource: app }
      type: STANDARD
      cidr: 10.100.10.0/24

  db_tier:
    type: Nuage::Neutron::ApplicationTier
    properties:
      name: db_tier
      app_id: { get_resource: app }
      type: STANDARD
      cidr: 10.100.20.0/24

  flow1:
    type: Nuage::Neutron::ApplicationFlow
    properties:
      name: webToDb
      origin_tier: { get_resource: web_tier }
      dest_tier: { get_resource: db_tier }
      nuage_services: [{ get_attr: [mysql_svc, name] }]

  web_port:
    type: Nuage::Neutron::ApplicationPort
    properties:
      name: web_port
      tier_id: { get_resource: web_tier }

  db_port:
    type: Nuage::Neutron::ApplicationPort
    properties:
      name: db_port
      tier_id: { get_resource: db_tier }

  web_server:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
       - port: { get_resource: web_port }

  db_server:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
       - port: { get_resource: db_port }

